workspace 'KoreBotSDK'
project 'KoreBotSDKDemo/KoreBotSDKDemo.xcodeproj'

inhibit_all_warnings!

def import_pods
    pod 'Mantle', '2.0.2'
    pod 'AFNetworking', '2.5.4'
end

target 'KoreBotSDKDemo' do
    platform :ios, '8.0'
    pod 'DTCoreText','1.6.15'
    pod 'Charts'

    use_frameworks!
    import_pods
    pod 'googleapis', :path=> '.'
    pod 'TOWebViewController'
    pod 'KoreBotSDK', :path => './Library/KoreBotSDK/'
    pod 'KoreWidgets', :path=> './Library/Widgets/'
    pod 'KoreTextParser', :path=> './Library/TextParser/'
    pod 'SpeechToText', :path=>'./Library/SpeechToText/'
    project 'KoreBotSDKDemo/KoreBotSDKDemo.xcodeproj'
end
