workspace 'KoreBotSDK'
project 'KoreBotSDK.xcodeproj'
project 'KoreBotSDKDemo/KoreBotSDKDemo.xcodeproj'
project 'SpeechToText/SpeechToText.xcodeproj'
project 'Widgets/Widgets.xcodeproj'

inhibit_all_warnings!

def import_pods
    pod 'Mantle', '2.0.2'
    pod 'AFNetworking', '2.5.4'
end

target 'KoreBotSDK' do
    platform :ios, '8.0'
    use_frameworks!
    project 'KoreBotSDK.xcodeproj'
end


target 'KoreBotSDKDemo' do
    platform :ios, '8.0'
    pod 'DTCoreText','1.6.15'

    use_frameworks!
    import_pods
    pod 'TOWebViewController'
    pod 'KoreBotSDK', :path => '.'
    pod 'KoreWidgets', :path=> './Widgets/'
    pod 'KoreTextParser', :path=> './TextParser/'
    pod 'SpeechToText', :path=>'./SpeechToText/'
    project 'KoreBotSDKDemo/KoreBotSDKDemo.xcodeproj'
end

target 'Widgets' do
    platform :ios, '8.0'
    pod 'AFNetworking', '2.5.4'
    
    use_frameworks!
    project 'Widgets/Widgets.xcodeproj'
end
