language: objective-c
xcode_workspace: Mantle.xcworkspace
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - set -o pipefail
  - xcodebuild $XCODE_ACTION
      -workspace "$TRAVIS_XCODE_WORKSPACE"
      -scheme "$TRAVIS_XCODE_SCHEME"
      -sdk "$XCODE_SDK"
      -destination "$XCODE_DESTINATION"
      RUN_CLANG_STATIC_ANALYZER=NO
      | xcpretty
matrix:
  include:
    - xcode_scheme: "Mantle Mac"
      osx_image: xcode8
      env:
        - XCODE_ACTION=test
        - XCODE_SDK=macosx
        - XCODE_DESTINATION="arch=x86_64"
    - xcode_scheme: "Mantle iOS"
      osx_image: xcode8
      env:
        - XCODE_ACTION=test
        - XCODE_SDK=iphonesimulator
        - XCODE_DESTINATION="name=iPhone 7"
    - xcode_scheme: "Mantle-tvOS"
      osx_image: xcode8
      env:
        - XCODE_ACTION=test
        - XCODE_SDK=appletvsimulator
        - XCODE_DESTINATION="name=Apple TV 1080p"
    - xcode_scheme: "Mantle-watchOS"
      osx_image: xcode8
      env:
        - XCODE_ACTION=build
        - XCODE_SDK=watchsimulator
        - XCODE_DESTINATION="name=Apple Watch - 38mm"
notifications:
  email: false
  campfire:
    on_success: always
    on_failure: always
    rooms:
    - secure: "QVVzkmaWyLgGMOgtaBF2EUQS3Ot1Bj7jc8CI7L1mqxrDpNnxtemgSNBkvFNrec0RoSMiHBY9t+aVdnHsCLlqhDs3mX55zxlbTJPDpFTVI2p77n90teuOr1kK+a3DYoyaxO6acrAJwhjOe6j9zd3o/su+VG5OsXqCXhBFfnc863w="
