workspace 'KoreBotSDKDemo'
project 'KoreBotSDKDemo/KoreBotSDKDemo.xcodeproj'

inhibit_all_warnings!

target 'KoreBotSDKDemo' do
    platform :ios, '10.0'

    use_frameworks!
    pod 'KoreBotSDK', :path => '../../'
    pod 'AssetsPickerViewController'
    pod 'SwiftUTI'
    project 'KoreBotSDKDemo.xcodeproj'
end
