workspace 'KoreBotSDKDemo'
project 'KoreBotSDKDemo/KoreBotSDKDemo.xcodeproj'

inhibit_all_warnings!

target 'KoreBotSDKDemo' do
    platform :ios, '11.0'

    use_frameworks!
    pod 'WidgetSDK', :path => '../../'
    project 'KoreBotSDKDemo.xcodeproj'
end
